#!/usr/bin/python
#-*- coding: utf-8 -*-

class Language:
    _LANGS = {
         "ab": "Abkhazian"
        ,"aa": "Afar"
        ,"af": "Afrikaans"
        ,"ak": "Akan"
        ,"sq": "Albanian"
        ,"am": "Amharic"
        ,"ar": "Arabic"
        ,"an": "Aragonese"
        ,"hy": "Armenian"
        ,"as": "Assamese"
        ,"av": "Avaric"
        ,"ae": "Avestan"
        ,"ay": "Aymara"
        ,"az": "Azerbaijani"
        ,"bm": "Bambara"
        ,"ba": "Bashkir"
        ,"eu": "Basque"
        ,"be": "Belarusian"
        ,"bn": "Bengali"
        ,"bh": "Bihari"
        ,"bi": "Bislama"
        ,"bs": "Bosnian"
        ,"br": "Breton"
        ,"bg": "Bulgarian"
        ,"my": "Burmese"
        ,"ca": "Catalan,Valencian"
        ,"ch": "Chamorro"
        ,"ce": "Chechen"
        ,"ny": "Chichewa,Chewa,Nyanja"
        ,"zh": "Chinese"
        ,"cv": "Chuvash"
        ,"kw": "Cornish"
        ,"co": "Corsican"
        ,"cr": "Cree"
        ,"hr": "Croatian"
        ,"cs": "Czech"
        ,"da": "Danish"
        ,"dv": "Divehi,Dhivehi,Maldivian"
        ,"nl": "Dutch,Flemish"
        ,"dz": "Dzongkha"
        ,"en": "English"
        ,"eo": "Esperanto"
        ,"et": "Estonian"
        ,"ee": "Ewe"
        ,"fo": "Faroese"
        ,"fj": "Fijian"
        ,"fi": "Finnish"
        ,"fr": "French"
        ,"ff": "Fulah"
        ,"gl": "Galician"
        ,"ka": "Georgian"
        ,"de": "German"
        ,"el": "Greek, Modern (1453–)"
        ,"gn": "Guarani"
        ,"gu": "Gujarati"
        ,"ht": "Haitian, Haitian Creole"
        ,"ha": "Hausa"
        ,"he": "Hebrew"
        ,"hz": "Herero"
        ,"hi": "Hindi"
        ,"ho": "Hiri Motu"
        ,"hu": "Hungarian"
        ,"id": "Indonesian"
        ,"ie": "Interlingue, Occidental"
        ,"ga": "Irish"
        ,"ig": "Igbo"
        ,"ik": "Inupiaq"
        ,"io": "Ido"
        ,"is": "Icelandic"
        ,"it": "Italian"
        ,"iu": "Inuktitut"
        ,"ja": "Japanese"
        ,"jv": "Javanese"
        ,"kl": "Kalaallisut, Greenlandic"
        ,"kn": "Kannada"
        ,"kr": "Kanuri"
        ,"ks": "Kashmiri"
        ,"kk": "Kazakh"
        ,"km": "Central Khmer"
        ,"ki": "Kikuyu, Gikuyu"
        ,"rw": "Kinyarwanda"
        ,"ky": "Kirghiz"
        ,"kv": "Komi"
        ,"kg": "Kongo"
        ,"ko": "Korean"
        ,"ku": "Kurdish"
        ,"kj": "Kuanyama, Kwanyama"
        ,"la": "Latin"
        ,"lb": "Luxembourgish, Letzeburgesch"
        ,"lg": "Ganda"
        ,"li": "Limburgan, Limburger, Limburgish"
        ,"ln": "Lingala"
        ,"lo": "Lao"
        ,"lt": "Lithuanian"
        ,"lu": "Luba-Katanga"
        ,"lv": "Latvian"
        ,"gv": "Manx"
        ,"mk": "Macedonian"
        ,"mg": "Malagasy"
        ,"ms": "Malay"
        ,"ml": "Malayalam"
        ,"mt": "Maltese"
        ,"mi": "Maori"
        ,"mr": "Marathi"
        ,"mh": "Marshallese"
        ,"mn": "Mongolian"
        ,"na": "Nauru"
        ,"nv": "Navajo, Navaho"
        ,"nd": "North Ndebele"
        ,"ne": "Nepali"
        ,"ng": "Ndonga"
        ,"nb": "Norwegian Bokmål"
        ,"nn": "Norwegian Nynorsk"
        ,"no": "Norwegian"
        ,"ii": "Sichuan Yi, Nuosu"
        ,"nr": "South Ndebele"
        ,"oc": "Occitan"
        ,"oj": "Ojibwa"
        ,"cu": "Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic"
        ,"om": "Oromo"
        ,"or": "Oriya"
        ,"os": "Ossetian"
        ,"pa": "Punjabi"
        ,"pi": "Pali"
        ,"fa": "Persian"
        ,"pl": "Polish"
        ,"ps": "Pashto"
        ,"pt": "Portuguese"
        ,"qu": "Quechua"
        ,"rm": "Romansh"
        ,"rn": "Rundi"
        ,"ro": "Romanian,Moldavian,Moldovan"
        ,"ru": "Russian"
        ,"sa": "Sanskrit"
        ,"sc": "Sardinian"
        ,"sd": "Sindhi"
        ,"se": "Northern Sami"
        ,"sm": "Samoan"
        ,"sg": "Sango"
        ,"sr": "Serbian"
        ,"gd": "Gaelic"
        ,"sn": "Shona"
        ,"si": "Sinhala"
        ,"sk": "Slovak"
        ,"sl": "Slovenian"
        ,"so": "Somali"
        ,"st": "Southern Sotho"
        ,"es": "Spanish"
        ,"su": "Sundanese"
        ,"sw": "Swahili"
        ,"ss": "Swati"
        ,"sv": "Swedish"
        ,"ta": "Tamil"
        ,"te": "Telugu"
        ,"tg": "Tajik"
        ,"th": "Thai"
        ,"ti": "Tigrinya"
        ,"bo": "Tibetan"
        ,"tk": "Turkmen"
        ,"tl": "Tagalog"
        ,"tn": "Tswana"
        ,"to": "Tonga"
        ,"tr": "Turkish"
        ,"ts": "Tsonga"
        ,"tt": "Tatar"
        ,"tw": "Twi"
        ,"ty": "Tahitian"
        ,"ug": "Uighur,Uyghur"
        ,"uk": "Ukrainian"
        ,"ur": "Urdu"
        ,"uz": "Uzbek"
        ,"ve": "Venda"
        ,"vi": "Vietnamese"
        ,"vo": "Volapük"
        ,"wa": "Walloon"
        ,"cy": "Welsh"
        ,"wo": "Wolof"
        ,"fy": "Western Frisian"
        ,"xh": "Xhosa"
        ,"yi": "Yiddish"
        ,"yo": "Yoruba"
        ,"za": "Zhuang,Chuang"
        ,"zu": "Zulu"
    }

    _ALPHA3 = {
         "ab": "abk"
        ,"aa": "aar"
        ,"af": "afr"
        ,"ak": "aka"
        ,"sq": "alb"
        ,"am": "amh"
        ,"ar": "ara"
        ,"an": "arg"
        ,"hy": "arm"
        ,"as": "asm"
        ,"av": "ava"
        ,"ae": "ave"
        ,"ay": "aym"
        ,"az": "aze"
        ,"bm": "bam"
        ,"ba": "bak"
        ,"eu": "baq"
        ,"be": "bel"
        ,"bn": "ben"
        ,"bh": "bih"
        ,"bi": "bis"
        ,"bs": "bos"
        ,"br": "bre"
        ,"bg": "bul"
        ,"my": "bur"
        ,"ca": "cat"
        ,"ch": "cha"
        ,"ce": "che"
        ,"ny": "nya"
        ,"zh": "chi"
        ,"cv": "chv"
        ,"kw": "cor"
        ,"co": "cos"
        ,"cr": "cre"
        ,"hr": "hrv"
        ,"cs": "cze"
        ,"da": "dan"
        ,"dv": "div"
        ,"nl": "dut"
        ,"dz": "dzo"
        ,"en": "eng"
        ,"eo": "epo"
        ,"et": "est"
        ,"ee": "ewe"
        ,"fo": "fao"
        ,"fj": "fij"
        ,"fi": "fin"
        ,"fr": "fre"
        ,"ff": "ful"
        ,"gl": "glg"
        ,"ka": "geo"
        ,"de": "ger"
        ,"el": "gre"
        ,"gn": "grn"
        ,"gu": "guj"
        ,"ht": "hat"
        ,"ha": "hau"
        ,"he": "heb"
        ,"hz": "her"
        ,"hi": "hin"
        ,"ho": "hmo"
        ,"hu": "hun"
        ,"ia": "ina"
        ,"id": "ind"
        ,"ie": "ile"
        ,"ga": "gle"
        ,"ig": "ibo"
        ,"ik": "ipk"
        ,"io": "ido"
        ,"is": "ice"
        ,"it": "ita"
        ,"iu": "iku"
        ,"ja": "jpn"
        ,"jv": "jav"
        ,"kl": "kal"
        ,"kn": "kan"
        ,"kr": "kau"
        ,"ks": "kas"
        ,"kk": "kaz"
        ,"km": "khm"
        ,"ki": "kik"
        ,"rw": "kin"
        ,"ky": "kir"
        ,"kv": "kom"
        ,"kg": "kon"
        ,"ko": "kor"
        ,"ku": "kur"
        ,"kj": "kua"
        ,"la": "lat"
        ,"lb": "ltz"
        ,"lg": "lug"
        ,"li": "lim"
        ,"ln": "lin"
        ,"lo": "lao"
        ,"lt": "lit"
        ,"lu": "lub"
        ,"lv": "lav"
        ,"gv": "glv"
        ,"mk": "mac"
        ,"mg": "mlg"
        ,"ms": "may"
        ,"ml": "mal"
        ,"mt": "mlt"
        ,"mi": "mao"
        ,"mr": "mar"
        ,"mh": "mah"
        ,"mn": "mon"
        ,"na": "nau"
        ,"nv": "nav"
        ,"nd": "nde"
        ,"ne": "nep"
        ,"ng": "ndo"
        ,"nb": "nob"
        ,"nn": "nno"
        ,"no": "nor"
        ,"ii": "iii"
        ,"nr": "nbl"
        ,"oc": "oci"
        ,"oj": "oji"
        ,"cu": "chu"
        ,"om": "orm"
        ,"or": "ori"
        ,"os": "oss"
        ,"pa": "pan"
        ,"pi": "pli"
        ,"fa": "per"
        ,"pl": "pol"
        ,"ps": "pus"
        ,"pt": "por"
        ,"qu": "que"
        ,"rm": "roh"
        ,"rn": "run"
        ,"ro": "rum"
        ,"ru": "rus"
        ,"sa": "san"
        ,"sc": "srd"
        ,"sd": "snd"
        ,"se": "sme"
        ,"sm": "smo"
        ,"sg": "sag"
        ,"sr": "srp"
        ,"gd": "gla"
        ,"sn": "sna"
        ,"si": "sin"
        ,"sk": "slo"
        ,"sl": "slv"
        ,"so": "som"
        ,"st": "sot"
        ,"es": "spa"
        ,"su": "sun"
        ,"sw": "swa"
        ,"ss": "ssw"
        ,"sv": "swe"
        ,"ta": "tam"
        ,"te": "tel"
        ,"tg": "tgk"
        ,"th": "tha"
        ,"ti": "tir"
        ,"bo": "tib"
        ,"tk": "tuk"
        ,"tl": "tgl"
        ,"tn": "tsn"
        ,"to": "ton"
        ,"tr": "tur"
        ,"ts": "tso"
        ,"tt": "tat"
        ,"tw": "twi"
        ,"ty": "tah"
        ,"ug": "uig"
        ,"uk": "ukr"
        ,"ur": "urd"
        ,"uz": "uzb"
        ,"ve": "ven"
        ,"vi": "vie"
        ,"vo": "vol"
        ,"wa": "wln"
        ,"cy": "wel"
        ,"wo": "wol"
        ,"fy": "fry"
        ,"xh": "xho"
        ,"yi": "yid"
        ,"yo": "yor"
        ,"za": "zha"
        ,"zu": "zul"
    }

    def __init__(self, pLang : str):
        """Validate "lang" against Alpha2 and Alpha3 codes"""
        self._name = None
        self._alpha2 = None
        self._alpha3 = None
        if not pLang is None:
            if not pLang in Language._LANGS:
                raise Exception("Invalid alpha2 language code '"+pLang+"'");
            self._name = Language._LANGS[pLang]
            self._alpha2 = pLang
            self._alpha3 = Language._ALPHA3[pLang]

    def getName(self):
        return self._name
    def name(self):
        return self._name

    def getAlpha2(self):
        return self._alpha2
    def alpha2(self):
        return self._alpha2

    def getAlpha3(self):
        return self._alpha3
    def alpha3(self):
        return self._alpha3

